apiVersion: batch/v1
kind: Job
metadata:
  name: doscont
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: cont2
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo cont2 > index.html && python -m http.server 8082']
      - name: cont3
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo cont3 > index.html && python -m http.server 8083']
      restartPolicy: OnFailure
    # The pod template ends here
