apiVersion: batch/v1
kind: Job
metadata:
  name: podtest2
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: cont2
        image: nginx:alpine
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
    # The pod template ends here
---
apiVersion: batch/v1
kind: Job
metadata:
  name: podtest3
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: cont3
        image: nginx:alpine
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
    # The pod template ends here    